export const experiences = [
  {
    company: "Simetrik",
    position: "Frontend Developer",
    startDate: "2024-04",
    endDate: "2025-05",
    description: "",
    technologies: ["ReactJS", "TypeScript", "NextJS"],
    methodology: "Agile",
    location: "Remote",
    url: "https://www.simetrik.com/",
    logo: "https://www.simetrik.com/images/logo.svg",
  },
  {
    company: "Innova",
    position: "Frontend Engineer",
    startDate: "2022-07",
    endDate: "2024-04",
    description: "",
    technologies: ["SAPUI5", "TypeScript", "ReactJS"],
    methodology: undefined,
    location: "Remote",
    url: "https://innovapps.net/",
    logo: "https://innovapps.net/wp-content/uploads/logo.svg",
  },
  {
    company: "Twnel",
    position: "Software Developer",
    startDate: "2021-01",
    endDate: "2022-07",
    description: "",
    technologies: ["JSON", "JavaScript", "Google Scripts"],
    methodology: "Agile",
    location: "Remote",
    url: "https://www.twnel.com/",
    logo: "https://www.twnel.com/wp-content/uploads/2019/03/twnel-logo.png",
  },
];
